### ISSUE TITLE
归档此项目，推荐使用 oceanPress_js

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/oceanpress_old#14]
@88250  我打算归档这个项目，改为使用 oceanPress_js 了。

待会我将 https://github.com/2234839/oceanPress_js 转移至 siyuan-note 下，你看可以不

**Comment by 88250** [comment]
建议将 oceanpress 换个名字，比如 oceanpress-old，然后再将 ocenpress_js 迁移过来改名为 oceanpress，old 里面更新一下 README，指向到新的地址。

**Comment by 2234839** [comment]
> 建议将 oceanpress 换个名字，比如 oceanpress-old，然后再将 ocenpress_js 迁移过来改名为 oceanpress，old 里面更新一下 README，指向到新的地址。

好的

**Comment by 2234839** [comment]
@88250 显示我没有权限转移
![图片](https://github.com/siyuan-note/oceanpress_old/assets/28727933/7e7a6b54-8c7e-4492-876a-a2a204a59920)

**Comment by 88250** [comment]
现在再试试看。

**Comment by 2234839** [comment]
> 现在再试试看。

可以了

**Comment by 88250** [comment]
好的，我把权限关掉了，repo 单独赋值权限给你。

**Comment by 2234839** [comment]
> 好的，我把权限关掉了，repo 单独赋值权限给你。

ok

**Comment by 88250** [comment]
另外，repo 我重命名了一下，使用全小写，应该不会有什么问题吧？

**Comment by 2234839** [comment]
> 另外，repo 我重命名了一下，使用全小写，应该不会有什么问题吧？

没有

**Comment by 88250** [comment]
好的，那就这样先，感谢贡献。
