### ISSUE TITLE
首页能不能美化一下,进去直接是个目录

### ISSUE THREAD

**Issue by hpp0hpp** [siyuan-note/oceanpress_old#9]
或者有没有办法显示侧边栏,像笔记一样展示侧边栏目录树

**Comment by Crowds21** [comment]
赞同. 而且现在笔记文件夹和文档已经不分家了.
或者每个文档生成html的时候开头插入一下上下级关系. 稍微显示一下上下级关系.
不知道大佬有没有时间.
